#!/usr/bin/env python
import pyfits as pf
import cPickle as pickle
import gzip
import sys
import re
from glob import glob

# Usage: feed in popler'ed _up_ file (done for MAKEE)
# arc-flux-header 2009-11-03-Flux-199_1-Hiltner600-11-_up_009.fits 
# print re.split('_|-', start)

popler_file, arc_file, flux_file = sys.argv[1],  sys.argv[2],  sys.argv[3]
print "Arc:", arc_file
print "Flux:", flux_file

outfile = '.'.join(popler_file.split('.')[:-1])
outfile = outfile + ".header"
print outfile

arc_hdu = pf.open(arc_file)
arc_header = {}

for key in arc_hdu[0].header.iterkeys():
    try:
    	arc_header[key] = arc_hdu[0].header[key]
    except:
    	pass

flux_hdu = pf.open(flux_file)
flux_header = {}
for key in flux_hdu[0].header.iterkeys():
    try:
    	flux_header[key] = flux_hdu[0].header[key]
    except:
    	pass

list_of_dictionaries = [arc_header, flux_header]

with gzip.open(outfile, 'wb') as file_handle:
    pickle.dump(list_of_dictionaries, file_handle, pickle.HIGHEST_PROTOCOL)
