#!/usr/bin/env python
import sys
import re
import numpy as np

def main(infile=sys.argv[1]):
  """docstring for main"""
  Nlist = []
  labelList = []
  with open(infile, 'r') as f13:
    beginBody = False
    for line in f13.read().splitlines():
      # Ignore comments and empty lines
      if (not line.strip().startswith('!') and (not line.strip().startswith('%')) and (line.strip() != '')): 
        if beginBody == True:
          Nlist.append(float(line.split()[1][:-2]))
          labelList.append(line.split()[2][-2:])
        if line.startswith('  *'):
          beginBody = True
  print labelList[np.argmax(Nlist)]
  pass
  
if __name__ == '__main__':
  main(sys.argv[1])