#!/usr/bin/env python
# freeshrek by Adrian Malec
# updated by Jonathan Whitmore
from urllib import urlopen
from re import findall
# Choose metric to judge "least busy"
METRIC = 'load_fifteen' # 'load_five', 'load_one'
# Sort all nodes by metric
ghtm = urlopen('http://green.ssi.swin.edu.au/ganglia/?m=%s&r=hour&s=ascending&c=Green+Machine' % METRIC).read()
sortedList = findall('<td>.+?alt="shrek([0-9]+).ssi.swin.edu.au".+?</td>', ghtm)
# The nodes that you are allowed to log into
allowedNodes = ['001','002','003','004','005','006','007','008','009','010','203','204','205','206','207','212','213','215','216']
# Send the least busy of the allowed nodes to stdout
print min(allowedNodes, key=sortedList.index)