#!/usr/bin/env python
# makee-reduction-script
# makee-reduction-script --arc_list arc1.list --science_list science1.list --flat_file flat.list
# Feed lists into MAKEE 

# Note that the flats file only looks at one file. 

import argparse
        
def main():
    """docstring for main"""
    parser = argparse.ArgumentParser(description='Parse.')
    #parser.add_argument('analysisFile', action="store", nargs='?', default='1fort.13', type=str) # Positional 
    parser.add_argument('--arc_list', action="store", nargs=1, help="slope, offset") # Positional
    parser.add_argument('--science_list', action="store", nargs=1, help="science files to go with") # Positional
    parser.add_argument('--flat_list', action="store", nargs=1, help="flat.") # Positional
    parser.add_argument('--object_name', action="store", nargs=1, default="astro", help="flat.") # Positional
    parser.add_argument('--starting_number', action="store", nargs=1, default="9", help="5") # Positional
    args = parser.parse_args()

    # MAKEE values
    eperdn=('1.9', '2.2', '2.2')
    ronoise=('2.8', '3.1', '3.1')

    # object_name = "Hiltner600"
    object_name = args.object_name
    # flat = ['raw/hires0147.fits']

    flats = []
    with open(args.flat_list) as fh:
        for row in fh.readlines():
            flats.append(row.strip())

    arcs = []
    with open(args.arc_list) as fh: 
        for row in fh.readlines():
            arcs.append(row.strip())

    sciences = []
    with open(args.science_list) as fh: 
        for row in fh.readlines():
            sciences.append(row.strip())
    # arc1 = ['raw/hires0192.fits']
    # science1 = ['raw/hires0188.fits', 'raw/hires0189.fits', 'raw/hires0190.fits', 'raw/hires0191.fits']

    number = int(args.starting_number)

    for arc in arcs:
        for science in sciences:
            number += 1
            for index, ccd in enumerate(range(1, 4)):
                rootname = object_name + "-" + str(number)
                print "makee", science, science, flat[0], arc, "-novac -nohc mode=1", "".join(["log=", rootname, "-", str(ccd),".log"]), 
                print "eperdn=" + eperdn[index], "ronoise=" + ronoise[index], "comm=-" + rootname, "pf=makee/makee.param ccd=" + str(ccd)


if __name__ == '__main__':
    main()
