#!/usr/bin/env python
# Quick script to parse and split on either - or _ and 

import string
import sys
import re
from glob import glob

parse_file = sys.argv[1]
parsed_name = re.split('_|-', parse_file )

if len(sys.argv) < 3:
    print "-".join(parsed_name[4:7]) + ".fits"
else:
    begin = int(sys.argv[2])
    end = int(sys.argv[3])
    print "*".join(parsed_name[begin:end]) + ".fits"

