#!/bin/bash

# $1 pdfnaming
# $2 startingfit
# $3 newfit

VELLABEL=$(bigNlabel $3)

echo $VELLABEL

printf "{fb,2};{tt,3};{vr,2}\npdf/$1.r\nvn/$VELLABEL/$1.v.pdf\n{df,2}\npdf/$1.d\nq\n" | fitcmp ./vpfit -o $2 -n $3 --scriptmode

gs -dNOPAUSE -sDEVICE=pdfwrite -sOUTPUTFILE=$1.r.pdf -dBATCH $1.r_*.pdf

gs -dNOPAUSE -sDEVICE=pdfwrite -sOUTPUTFILE=$1.d.pdf -dBATCH $1.d_*.pdf

rm $1.r_*.pdf

rm $1.d_*.pdf
