#!/bin/bash

# $1 pdfnaming
# $2 startingfit
# $3 newfit
# $4 largest Ncolumn z-flag

printf "{fb,2}\npdf/$1\nq\n" | fitcmp vpfit -o $2 -n $3 --nonfancy

# printf "{fb,2}\n{vr,2}\n{tt,3}\nvn/$4/vel.$1.pdf/$1\nq\n" | fitcmp vpfit -o $2 -n $3 --nonfancy

gs -dNOPAUSE -sDEVICE=pdfwrite -sOUTPUTFILE=$1.pdf -dBATCH $1*.pdf

