#!/bin/bash

# $1 pdfnaming
# $2 startingfit
# $3 newfit

printf "{fb,2}\n{tt,3}\npdf/$1\nq\n" | fitcmp vpfit -o $2 -n $3 --nonfancy

gs -dNOPAUSE -sDEVICE=pdfwrite -sOUTPUTFILE=$1.r.pdf -dBATCH $1_*.pdf

VELLABEL=$(bigNlabel $3)

echo largest component: $VELLABEL

printf "{fb,2}\n{vr,2}\n{tt,3}\nvn/$VELLABEL/$1.v.pdf\nq\n" | fitcmp vpfit -o $2 -n $3 --nonfancy