#!/bin/bash
# Takes the inputfiles.list (full paths)
# MAKEE reduced, solar spectrum

# Checks if telluric lines a system variable.

if [ -z "$POPLER_TELLURIC" ]
then
    echo "Please set up sky lines environment variable."
    echo "POPLER_TELLURIC=\"path_to_telluric.dat\""
    echo "export POPLER_TELLURIC" 
    exit
else
    UVES_popler $1 -raw -save 2 -filetype 2 -atmomask $POPLER_TELLURIC -disp 1.30 
fi
