#!/bin/bash
# removes lines from both lowercase and UPPERCASE of input
# $ removeComponent af oldfort.13 newfort.13
# removes lines containing af and AF 
# $1 line
# $2 oldfort.13
# $3 newfort.13

trigger2=$(echo $1 | tr '[a-z]' '[A-Z]')
echo "Removing: " $1 $trigger2
grep -v $1 $2 | grep -v $trigger2 > $3