#!/bin/bash
# Usage: 
# sim-vpfit vlt-transitions.txt ion-abundance.txt vlt-da.txt simulation-base.config UVES
# sim-vpfit keck-transitions.txt ion-abundance.txt keck-da.txt simulation-base.config HIRES

TRANSITIONS=$1 # keck-transitions.txt
IONABUNDANCE=$2 # ion-abundance.txt
ALPHALIST=$3 # keck-da.txt
SIMCONFIG=$4 # simulation-base.config
SPECTROGRAPH=$5 # HIRES

export ATOMDIR=/Users/jwhitmore/Dropbox/Research/Fitting/Dipole/MM_2013-07-01_H2.dat
export VPFSETUP=/Users/jwhitmore/Dropbox/Research/Fitting/Dipole/jw_vp_setup.dat

if [ ! -f $ATOMDIR ]; then
    echo "atom.dat not found!"
    exit 0
fi
if [ ! -f $VPFSETUP ]; then
    echo "vpsetup not found!"
    exit 0
fi

STARTINGDIR=$(pwd)
echo Starting directory: $STARTINGDIR

for directory in $(cat $SPECTROGRAPH.directories.list);
do
    cd $directory
    printf "f\nil\nn\n0.005\nb\n0.10\nz\n1.e-6\nx4\n1.e-6\n\n\nsim_fort.13\nn\n\n" > sim.vpfitcommand
    vpfit10 < sim.vpfitcommand && cp fort.18 sim_fort.18 && cp fort.26 sim_fort.26
    pycombine2613 sim_fort.13 sim_fort.26 > sim_fit.13
    convertda2 sim_fit.13 > sim_alpha.13
    printf "f\nil\nn\n0.005\nb\n0.10\nz\n1.e-6\nx4\n1.e-6\n\n\nsim_alpha.13\nn\n\n" > sim_alpha.vpfitcommand
    vpfit10 < sim_alpha.vpfitcommand && cp fort.18 sim_alpha.18 && cp fort.26 sim_alpha.26
    pycombine2613 sim_alpha.13 sim_alpha.26 > sim_alphafit.13
done
