#!/bin/bash

TRANSITIONS=$1 # keck-transitions.txt
IONABUNDANCE=$2 # ion-abundance.txt
ALPHALIST=$3 # keck-da.txt
SIMCONFIG=$4 # simulation-base.config
SPECTROGRAPH=$5 # HIRES
RUNNUMBER=$6 # 
SLOPE=$7 
OFFSET=$8

export ATOMDIR=/Users/jwhitmore/Dropbox/Research/Fitting/Dipole/MM_2013-07-01_H2.dat
export VPFSETUP=/Users/jwhitmore/Dropbox/Research/Fitting/Dipole/jw_vp_setup.dat

if [ ! -f $ATOMDIR ]; then
    echo "atom.dat not found!"
    exit 0
fi
if [ ! -f $VPFSETUP ]; then
    echo "vpsetup not found!"
    exit 0
fi

STARTINGDIR=$(pwd)
echo Starting directory: $STARTINGDIR

DISTORTNAME=linear.$RUNNUMBER

cd $STARTINGDIR
for directory in $(cat $SPECTROGRAPH.directories.list);
do
    regionshift $directory/sim_fit.13 --linear $SLOPE $OFFSET > $directory/$DISTORTNAME.fort.13
done
cd $STARTINGDIR

for directory in $(cat $SPECTROGRAPH.directories.list);
do
    cd $directory
    printf "f\nil\nn\n0.005\nb\n0.10\nz\n1.e-6\nx4\n1.e-6\n\n\n$DISTORTNAME.fort.13\nn\n\n" > $DISTORTNAME.vpfitcommand
    vpfit10 < $DISTORTNAME.vpfitcommand && cp fort.18 $DISTORTNAME.fort.18 && cp fort.26 $DISTORTNAME.fort.26
    pycombine2613 $DISTORTNAME.fort.13 $DISTORTNAME.fort.26 > $DISTORTNAME.fit.13    
    convertda2 $DISTORTNAME.fit.13 > $DISTORTNAME.alpha.13
    printf "f\nil\nn\n0.005\nb\n0.10\nz\n1.e-6\nx4\n1.e-6\n\n\n$DISTORTNAME.alpha.13\nn\n\n" > $DISTORTNAME.alpha.vpfitcommand
    vpfit10 < $DISTORTNAME.alpha.vpfitcommand  && cp fort.18 $DISTORTNAME.alpha.18 && cp fort.26 $DISTORTNAME.alpha.26
    pycombine2613 $DISTORTNAME.alpha.13 $DISTORTNAME.alpha.26 > $DISTORTNAME.alpha.fit.13
done
cd $STARTINGDIR

echo "#J2000 redshift daa daa_error" > $SPECTROGRAPH.$DISTORTNAME.alpha
echo "#--linear $SLOPE $OFFSET" >> $SPECTROGRAPH.$DISTORTNAME.alpha
for infile in $SPECTROGRAPH/*/*/$DISTORTNAME.alpha.26
do 
    newname=$(echo $infile | awk 'BEGIN{FS="/"}{print $1, $2, $3, $4}')
    echo $newname | awk '{printf("%s\t%s\t"), $2, $3}' >> $SPECTROGRAPH.$DISTORTNAME.alpha
    awk 'BEGIN{OFS="\t"}/qa/{print $8, $9}' $infile | sed -e 's/a//g' -e 's/q//g' >> $SPECTROGRAPH.$DISTORTNAME.alpha
done
cd $STARTINGDIR
